reset;
model kidneys3.mod;
data kidneys3.dat;
option solver cplex; # Using full version ampl-cplex
option cplex_options 'timing=1 timelimit=120 mipemphasis=2 integrality=0.4 cutpass=-1 time=120';
solve;
# print {i in DONORS}: {j in DONORS} visualization_aid[i,j] > kidneys3.out;
display num_exchanges;
display sum {(i,j) in TWO_CYCLES} (2 * two_var[i,j]);
display sum {(i,j,k) in THREE_CYCLES} (3 * three_var[i,j,k]);